# Generated by Django 4.1.2 on 2022-10-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-name',)},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='title',
            new_name='name',
        ),
    ]
